# template.yaml - NCA Toolkit (baseado na imagem oficial)
name: nca-toolkit
description: Deploy do NCA Toolkit usando a imagem oficial do Docker
version: 1.0.0
author: SeuNome
logo: https://raw.githubusercontent.com/easypanel-io/templates/main/logo.png
repository: https://github.com/easypanel-io/templates

# Imagem oficial do Docker
image: ncatech/nca-toolkit:latest

# Portas que serão expostas
ports:
  - 3000:3000  # Interface web do NCA Toolkit
  - 5678:5678  # Porta interna se precisar de integração interna

# Variáveis de ambiente necessárias
env:
  - name: NCA_SECRET_KEY
    description: Chave secreta para autenticação
    required: true
  - name: NCA_DB_URL
    description: URL do banco de dados (PostgreSQL recomendado)
    required: true
  - name: NCA_API_URL
    description: URL base da API
    required: false

# Comando de inicialização padrão
start:
  cmd: ["nca-toolkit"]
  description: Inicia o NCA Toolkit

# Volumes persistentes (opcional)
volumes:
  - name: nca-data
    description: Dados persistentes do NCA Toolkit
    path: /app/data

# Healthcheck básico
healthcheck:
  cmd: curl -f http://localhost:3000/ || exit 1
  interval: 30s
  retries: 3
